### ISSUE TITLE
[REQUEST] allow push for branches so I can contribute to the repo

### ISSUE THREAD

**Issue by butzhang** [imelnyk/ArxivPapers#2]
<img width="1041" alt="image" src="https://github.com/imelnyk/ArxivPapers/assets/4190704/c85e9740-7c22-4bf2-bcdf-2458f0bd1b47">

Hi, I am trying to add PR to better manage the dependencies so people to easily install them.
However I can't push my changes to other branches so I can't create a PR.
<img width="742" alt="image" src="https://github.com/imelnyk/ArxivPapers/assets/4190704/597547c6-ad78-41b3-8565-304cecfacc57">

**Comment by imelnyk** [comment]
Hi, thanks for trying to contribute to this project! Maybe I misunderstood you, but I am not sure what is the issue. Can you clone the repo, make changes there or create a new branch locally, then commit and push the changes. And then create a pull request, which I can review and merge. 
Can you try if this works for you?

**Comment by butzhang** [comment]
Yeah, I can try it of course if that works for you. I thought normally people will create a branch in YOUR own repo and I will create a PR in your repo instead of my repo. 
for example: https://github.com/leptonai/search_with_lepton/pulls

you are the only one who can merge pr into main, but allow others push other branches.
