### ISSUE TITLE
How do you get the most impactful paper on Arxiv?

### ISSUE THREAD

**Issue by huanranchen** [imelnyk/ArxivPapers#4]
There are so many papers on arxiv everyday, how do you select the most impactful one?

**Comment by imelnyk** [comment]
Hi, it is mostly going through arxiv.org and looking daily for "good" papers (also I use twitter, reddit, etc)

**Comment by huanranchen** [comment]
> Hi, it is mostly going through arxiv.org and looking daily for "good" papers (also I use twitter, reddit, etc)

Thanks!
